### ISSUE TITLE
Can’t install Ifile for step 2?

### ISSUE THREAD

**Issue by WinchesterJo** [KirovAir/delectra#10]
I really don’t know how I can do this without some form of help?

[URL=http://s203.photobucket.com/user/Jo_Winchester/media/E6A0A8A0-D048-4B0A-8501-D40A357449E4.png.html][IMG]http://i203.photobucket.com/albums/aa293/Jo_Winchester/th_E6A0A8A0-D048-4B0A-8501-D40A357449E4.png[/IMG][/URL]

I get this when I try to install ifile to do step 2.

I also can’t see my installed programmes or tweaks in cydia. The section is completely empty!?

That and I get these errors a lot when cydia loads repo lists ->

[URL=http://s203.photobucket.com/user/Jo_Winchester/media/IMG_0011_1.png.html][IMG]http://i203.photobucket.com/albums/aa293/Jo_Winchester/th_IMG_0011_1.png[/IMG][/URL]

Any help would be appreciated because I’m completely lost

**Comment by jabesmartinez** [comment]
Go on YouTube an search up delectra I had same problems like you an follow steps one of the videos with a Mac if you have one or there’s one with a pc

**Comment by jabesmartinez** [comment]
Also There’s Filzaescaped I’m tweakbox app

**Comment by WinchesterJo** [comment]
I’ve really tried just about everything now and all I need to do is run unjailbreak.sh. But I don’t know HOW?

Could you tell me how to shh into my phone, so I can run this?

**Comment by jabesmartinez** [comment]
Did you follow steps in video

**Comment by WinchesterJo** [comment]
I’ve tried with cyber duck? It connected and downloaded the unjailbreak.sh from the /Electra file.

I don’t know how to run it from my desktop tho?

**Comment by jabesmartinez** [comment]
What type of computer do you have

**Comment by WinchesterJo** [comment]
It’s pc on windows 10

**Comment by jabesmartinez** [comment]
Did you watch the video on delectra by the jailbreaker an you have to download putty go to that video by the jailbreaker an watch each step carefully

**Comment by WinchesterJo** [comment]
Ok so everything is now gone. For Electra and rejailbreak, should I stick to Electra 1.0.2 or 0.3 tho?

**Comment by jabesmartinez** [comment]
It’s up to you glad it worked

**Comment by WinchesterJo** [comment]
Thanx so much!

**Comment by jabesmartinez** [comment]
No problem I glad I was able to help since I had the same problem 3 weeks ago
