### ISSUE TITLE
[Enhancement] Update for the iOS 11.3.1 Electra Jailbreak

### ISSUE THREAD

**Issue by TheRealKeto** [KirovAir/delectra#12]
I'm sure there will be a few things changed in Electra in order to fix the remount issue, so I think this should get an update once Electra is fully released. While this tool/script can be dangerous throughout it's early stages of being updated, I hope it isn't too hard to update.

**Comment by iambenmitchell** [comment]
I am on 11.3.1 messed up Cydia. Although I doubt this removed EVERYTHING it manage to trigger electra 11.3.1 to re install

**Comment by andrescouvel** [comment]
so, it works on Electra 11.3.1?

**Comment by How-Bout-No** [comment]
delectra seems to mostly work on Electra 11.3.1

**Comment by sohail199** [comment]
Can any one please confirm whether this works with ios 11.3.1 jailbreak?

**Comment by ghost** [comment]
Yes its working

iPX 11.3.1

**Comment by KirovAir** [comment]
Hi guys,

In theory the script should still work but I'll make sure to double-check the electra installation when I have a moment tonight or tomorrow. :) Thanks for testing!

**Comment by TheRealDugan** [comment]
I have tested this and it seems to work however I don’t think it completely removes everything that the jailbreak originally installs but it will work if your trying to reset Cydia. I tested it and when I tried a couple of apps I found that the jailbreak detection is still on (etc., Fortnite PokemonGo).

**Comment by trungnguyen21** [comment]
Will this delete all my device’s data? 

Edit: spelling

**Comment by sohail199** [comment]
No it will only delete Cydia from your device.
I you want to remove Cydia first uninstall substitute from Cydia and then use delectra.

**Comment by WestCrow** [comment]
Work for me
iPad Mini 4 11.3.1

**Comment by andrescouvel** [comment]
Works perfect on 11.3.1 iPhone 7

**Comment by cheechmaria** [comment]
I've been trying to use Delectra for my i7+ on 11.3.1 but It will not delete Cydia to save the life of me! I've tried putting the .sh file into /root and in /electra and just root/ and with variations of the command but cannot get it to work :( https://imgur.com/gallery/34M1lyH

**Comment by cheechmaria** [comment]
I actually have deleted all tweaks in Cydia except for zip and pincrush (located in 'Expert' tab) but it won't let me delete them. "dpkg warning 'rm' not found in path or not executable" in Cydia

**Comment by fugidev** [comment]
@cheechmaria the script has already removed 'rm' which is used to remove things. That's whats causing the errors. Have you tried rejailbreaking and running unjailbreak.sh again (as root)? If that does not work try placing rm in its appropriate directory again.

**Comment by cheechmaria** [comment]
@FugiMuffi Yes I've tried rejailbreaking it and re running the script but I'm not sure where 'rm' is and what directory it should go into?

**Comment by cheechmaria** [comment]
@FugiMuffi Yes I've tried rejailbreaking it and re running the script but I'm not sure where 'rm' is, and what directory it should go into? 
**Update:** wait I think I know what you mean.. Line 505 of the script is 'rm -f /bin/rm' which is what I think you mean. And looking in /bin with Cyberduck- there is no rm file :/ idk what that means/what I should do

**Comment by fugidev** [comment]
rm is included in Core Utilities (/bin), can you try (re)installing that?

**Comment by cheechmaria** [comment]
@FugiMuffi Yea I'm sure I could I just don't know how I'd do that lol

**Comment by cheechmaria** [comment]
If it's something I have to download from Cydia then RIP bc I cannot download anything from it which is why I wanted to fresh jailbreak my phone :/
https://imgur.com/7Z5mFpI

**Comment by fugidev** [comment]
I uploaded rm from my filesystem: https://mega.nz/#!O4ZxgQxC!CMssITx4AM6euL2GB5jUshPR3wnT-3bwhQRDiN0qHJc
Try placing it in /bin and chmod 755 it.
Then try running delectra.sh again

**Comment by cheechmaria** [comment]
@fugimuffi thank you so much, I didn't mean all this trouble. It says -sh chmod: command not found 😂feels bad

**Comment by fugidev** [comment]
I‘m afraid you‘re out of luck then. You could add chmod as well but it wouldn‘t work without making it executable.

**Comment by cheechmaria** [comment]
Oh ok :/ thanks for all your help. When Coolstar updates a semirestore would that help, or I guess I wouldn't be able to download it? Should I erase all content and settings to rid of the jailbreak or that'd probably create more issues than fix. Or I'm probably better off updating to 11.4.1 and waiting for that jailbreak? 🙄 Also thanks for all your help and time, very kind of you

**Comment by KirovAir** [comment]
@cheechmaria Can you remove files using cyberduck? 
Can you check if the file .bootstrapped_electra is present in the root of your device? If so you can try deleting that one and reboot and rejailbreak. In electra 11.1.2 that would re-trigger basebinary extraction which should put the core binaries back. But I can not view the 11.3.1 code so I'm not 100% sure.

**Comment by cheechmaria** [comment]
@KirovAir yes I can remove files via Cyberduck! I will try that once I'm home and try that. Im pretty sure Delectra deleted the bootstrap folder but I will definitely check it out tomorrow and troubleshoot some more!

**Comment by cheechmaria** [comment]
@KirovAir .bootstrapped_electra was present (but it was 0KB idk if that matters) and once I rebooted it, Electra said Jailbreak and not Enable jailbreak! But when using Cyberduck there's nothing in the cores folder. I can run the ./unjailbreak.sh but it says /bin/rm: permission denied. I have tried typing 'chmod 775 ./unjailbreak.sh' but it doesn't seem to help

**Comment by iM4CH3T3** [comment]
This should help to find out what everything electra 1131 is placing in the file system ...
https://pastebin.com/KkmzbvuB

**Comment by iM4CH3T3** [comment]
Check this tweet for more info ...

https://twitter.com/razmashat/status/1018607051491115008?s=21

**Comment by cheechmaria** [comment]
Okay I feel somwhat stupid but Idc because I finally got it to work! I accidentally did chmod 775 instead of chmod 755. Thank you all for your help and patience. @FugiMuffi thank you for your help and @KirovAir for the advice of deleting .bootstrapped_electra This is what's great about the kind JB community!

**Comment by fugidev** [comment]
Glad I could help!

**Comment by saitawngpha** [comment]
Amazing Tools to remove Electra Jail. It's working for me iPhone 7, ios 11.3.1. Thank for dev.
