### ISSUE TITLE
Let the script delete itself

### ISSUE THREAD

**Issue by fanckush** [KirovAir/delectra#16]
Shouldn't the script delete itself after everything is successful?

**Comment by Patrickk17** [comment]
If the script deleted itself that would leave rm left over since the script would stop before it could delete rm; and if you made the script delete itself after it deletes rm it wouldn’t work since rm wouldn’t exist

**Comment by KirovAir** [comment]
If you place it in the /electra dir it will delete itself. :)

**Comment by fanckush** [comment]
Cool, but shouldn't that be the default location then?

**Comment by KirovAir** [comment]
It's in the readme:

> Put unjailbreak.sh on your phone. I'd recommend putting it in /electra so it will be removed by itself
