### ISSUE TITLE
WinSCP loses connection before: read -p "Press enter to continue. Press Ctrl + C to exit" 

### ISSUE THREAD

**Issue by ghost** [KirovAir/delectra#4]
WinSCP loses connection before the line: read -p "Press enter to continue. Press Ctrl + C to exit" . I have tried using the beta and non beta versions of electra.

**Comment by ghost** [comment]
When I was jailbroken with Electra 1.0.2 none of the tweaks I installed showed up in settings. To fix this I tried to run the delectra script.

When I try to run the delectra script I get to the line before the line 'read -p "Press enter to continue. Press Ctrl + C to exit" ' and winSCP crashes/disconnects.

I copied the source and pasted into putty to see if that would work and now I get a topanga error when I try to jailbreak, probably because not all of the script was run.

**Comment by KirovAir** [comment]
Have you tried running the script without pasting in putty but just running it using ‘bash’ or ‘sh’ unjailbreak.sh?

I’ve had more reports about winscp not working correctly so I might need to add that to the readme.

**Comment by ghost** [comment]
Yeah, I tried that on putty and it said file not found. It was in the right directory. Ended up using MTerminal on my iPhone and it worked fine.

**Comment by KirovAir** [comment]
That's good to hear! I'll close the issue then. :)
