### ISSUE TITLE
Tweaks are not working!

### ISSUE THREAD

**Issue by Db15123** [KirovAir/delectra#6]
Hey,
I’ve just successfully deleted Electra Version 1.0.2, then I reinstalled Electra and first there was a topanga error, after checking your GitHub I deleted the files with Filza. Then it worked, cydia was there and I thought everything is working but tweaks are not working, but things like Icleaner and Ext3nder are working. I already tried to reinstall the tweak (Cylinder) and Substitute but it didn’t worked! I’ve Used the Comand: „mkdir /Library/Frameworks/ “  I Ssh in my device with The app NewTerm (Terminal).
And there was a error: „cannot create directory“ and „file exists“. How can I get tweak working? Thank you

**Comment by bpluhar** [comment]
Start fresh by rerunning `unjailbreak.sh`, then reinstall Electra 1.0.3.

When Cydia opens, make sure you install Substitute, Substrate Compability Layer as well as APT 0.7 (lib) (from Coolstar). Do **NOT** let Cydia install the Essential Updates as that will render Cydia unusable.
