### ISSUE TITLE
Deelectra Questions

### ISSUE THREAD

**Issue by jacc** [KirovAir/delectra#7]
1. How do I delete all user tweaks?
2. Is it safe to Erase all Content and Settings after using it?

Thank you!

**Comment by jabesmartinez** [comment]
Do you know if anyone has made a video on how to do this don’t know how to run unjailbreak.sh

**Comment by KirovAir** [comment]
@jacc 
1. Remove all tweaks you installed by yourself. 
2. Yes, this should cause no problems.

@jabesmartinez Someone on reddit has posted a video somewhere.

**Comment by jacc** [comment]
@KirovAir I read somewhere that uninstalling/reinstalling Substitute was the easiest way to remove all user installed tweaks. Is this true?

**Comment by KirovAir** [comment]
Yes most tweaks depend on Substitute/TweakInjector so that will uninstall most tweaks. But don't forget to also remove RocketBootstrap etc. Just about anything you installed yourself.

**Comment by jabesmartinez** [comment]
@KirovAir do you mind linking me to the post I’ve looked for answers and videos but no luck

**Comment by jacc** [comment]
@kirovair would there be anyway to implement a feature to delete all user installed tweaks? i’m mad lazy to remove all of them manually and the Substitute/RB method seems hella sketchy

**Comment by KirovAir** [comment]
@jacc Currently semirestore11-lite is out. You can use that. 

@jabesmartinez https://www.youtube.com/watch?v=PyzpkZfZRpA
